num_layers: 3
dim_feedforward: 64
dropout: 0.1
chunk_size: 7500
overlap: 2000
conv_kernel_size: 1000
initial_length: 30000
target_len: 15000
batch_size: 6
epochs: 50
learning_rate: 0.0001
train_test_split: 0.8
rasterization_downsample_factor: 2
checkpoint_interval: 1